import type { SubcircuitProps } from "@tscircuit/props";
import { Fragment } from "react";
import { AWR1843ARBGALPQ1 } from "../chips/AWR1843ARBGALPQ1.circuit.tsx";
import { CHS01TA } from "../chips/CHS01TA.circuit.tsx";

const SOURCE_SCALE = 0.0254;
const POWER_SHEET_OFFSET_X = 45;

const toSchX = (sourceX: number, sheet: "io" | "power") =>
  (sourceX - 850) * SOURCE_SCALE +
  (sheet === "power" ? POWER_SHEET_OFFSET_X : 0);

const toSchY = (sourceY: number) => (sourceY - 550) * SOURCE_SCALE;

const AWR_UNIT_BOUNDS = [
  { unit: "U2A", sheet: "io", left: 780, bottom: 610, right: 950, top: 900 },
  { unit: "U2B", sheet: "io", left: 680, bottom: 230, right: 910, top: 480 },
  {
    unit: "U2C",
    sheet: "power",
    left: 200,
    bottom: 590,
    right: 380,
    top: 1030,
  },
  { unit: "U2D", sheet: "power", left: 140, bottom: 100, right: 180, top: 490 },
  { unit: "U2E", sheet: "power", left: 320, bottom: 90, right: 360, top: 490 },
] as const;

const AWR_UNIT_PINS = [
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 1,
    ball: "A1",
    signal: "VSS",
    bodyX: 180,
    bodyY: 470,
    externalX: 200,
    externalY: 470,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 2,
    ball: "A2",
    signal: "VSS",
    bodyX: 180,
    bodyY: 460,
    externalX: 200,
    externalY: 460,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 3,
    ball: "A3",
    signal: "DP11",
    bodyX: 950,
    bodyY: 770,
    externalX: 970,
    externalY: 770,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 4,
    ball: "A4",
    signal: "DP13",
    bodyX: 950,
    bodyY: 750,
    externalX: 970,
    externalY: 750,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 5,
    ball: "A5",
    signal: "VIN_SRAM_3",
    bodyX: 200,
    bodyY: 600,
    externalX: 180,
    externalY: 600,
    direction: "left",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 6,
    ball: "A6",
    signal: "VSSA",
    bodyX: 180,
    bodyY: 250,
    externalX: 200,
    externalY: 250,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 7,
    ball: "A7",
    signal: "CLKP",
    bodyX: 780,
    bodyY: 670,
    externalX: 760,
    externalY: 670,
    direction: "left",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 8,
    ball: "A8",
    signal: "VSSA",
    bodyX: 180,
    bodyY: 240,
    externalX: 200,
    externalY: 240,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 9,
    ball: "A9",
    signal: "VOUT_14SYNTH",
    bodyX: 380,
    bodyY: 880,
    externalX: 400,
    externalY: 880,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 10,
    ball: "A10",
    signal: "VOUT_14APLL",
    bodyX: 380,
    bodyY: 890,
    externalX: 400,
    externalY: 890,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 11,
    ball: "A11",
    signal: "VSSA",
    bodyX: 180,
    bodyY: 230,
    externalX: 200,
    externalY: 230,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 12,
    ball: "A12",
    signal: "VIN_18VCO",
    bodyX: 200,
    bodyY: 650,
    externalX: 180,
    externalY: 650,
    direction: "left",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 13,
    ball: "A13",
    signal: "VSSA",
    bodyX: 180,
    bodyY: 220,
    externalX: 200,
    externalY: 220,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 14,
    ball: "A14",
    signal: "OSC_CLKOUT",
    bodyX: 780,
    bodyY: 830,
    externalX: 760,
    externalY: 830,
    direction: "left",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 15,
    ball: "A15",
    signal: "VSSA",
    bodyX: 180,
    bodyY: 210,
    externalX: 200,
    externalY: 210,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 16,
    ball: "A16",
    signal: "VBGAP",
    bodyX: 200,
    bodyY: 930,
    externalX: 180,
    externalY: 930,
    direction: "left",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 17,
    ball: "A17",
    signal: "VSSA",
    bodyX: 180,
    bodyY: 200,
    externalX: 200,
    externalY: 200,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 18,
    ball: "A18",
    signal: "VSSA",
    bodyX: 180,
    bodyY: 190,
    externalX: 200,
    externalY: 190,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 19,
    ball: "B1",
    signal: "VIOIN_18_3",
    bodyX: 200,
    bodyY: 850,
    externalX: 180,
    externalY: 850,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 20,
    ball: "B2",
    signal: "SPI_HOST_INTR_1",
    bodyX: 910,
    bodyY: 310,
    externalX: 930,
    externalY: 310,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 21,
    ball: "B3",
    signal: "DP9",
    bodyX: 950,
    bodyY: 790,
    externalX: 970,
    externalY: 790,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 22,
    ball: "B4",
    signal: "DP12",
    bodyX: 950,
    bodyY: 760,
    externalX: 970,
    externalY: 760,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 23,
    ball: "B5",
    signal: "DP15",
    bodyX: 950,
    bodyY: 730,
    externalX: 970,
    externalY: 730,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 24,
    ball: "B6",
    signal: "VSSA",
    bodyX: 180,
    bodyY: 180,
    externalX: 200,
    externalY: 180,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 25,
    ball: "B7",
    signal: "CLKM",
    bodyX: 780,
    bodyY: 660,
    externalX: 760,
    externalY: 660,
    direction: "left",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 26,
    ball: "B8",
    signal: "VSSA",
    bodyX: 180,
    bodyY: 170,
    externalX: 200,
    externalY: 170,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 27,
    ball: "B9",
    signal: "VSSA",
    bodyX: 180,
    bodyY: 160,
    externalX: 200,
    externalY: 160,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 28,
    ball: "B10",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 470,
    externalX: 380,
    externalY: 470,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 29,
    ball: "B11",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 460,
    externalX: 380,
    externalY: 460,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 30,
    ball: "B12",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 450,
    externalX: 380,
    externalY: 450,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 31,
    ball: "B13",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 440,
    externalX: 380,
    externalY: 440,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 32,
    ball: "B14",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 430,
    externalX: 380,
    externalY: 430,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 33,
    ball: "B15",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 420,
    externalX: 380,
    externalY: 420,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 34,
    ball: "B16",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 410,
    externalX: 380,
    externalY: 410,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 35,
    ball: "B17",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 400,
    externalX: 380,
    externalY: 400,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 36,
    ball: "B18",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 390,
    externalX: 380,
    externalY: 390,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 37,
    ball: "C1",
    signal: "VNWA_3",
    bodyX: 380,
    bodyY: 990,
    externalX: 400,
    externalY: 990,
    direction: "right",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 38,
    ball: "C2",
    signal: "SPI_CS_1",
    bodyX: 910,
    bodyY: 360,
    externalX: 930,
    externalY: 360,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 39,
    ball: "C3",
    signal: "DP8",
    bodyX: 950,
    bodyY: 800,
    externalX: 970,
    externalY: 800,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 40,
    ball: "C4",
    signal: "DP10",
    bodyX: 950,
    bodyY: 780,
    externalX: 970,
    externalY: 780,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 41,
    ball: "C5",
    signal: "DP14",
    bodyX: 950,
    bodyY: 740,
    externalX: 970,
    externalY: 740,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 42,
    ball: "C6",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 380,
    externalX: 380,
    externalY: 380,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 43,
    ball: "C7",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 370,
    externalX: 380,
    externalY: 370,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 44,
    ball: "C8",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 360,
    externalX: 380,
    externalY: 360,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 45,
    ball: "C9",
    signal: "GPADC_5",
    bodyX: 950,
    bodyY: 670,
    externalX: 970,
    externalY: 670,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 46,
    ball: "C10",
    signal: "GPADC_6",
    bodyX: 950,
    bodyY: 660,
    externalX: 970,
    externalY: 660,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 47,
    ball: "C11",
    signal: "VIN_18VCO",
    bodyX: 200,
    bodyY: 640,
    externalX: 180,
    externalY: 640,
    direction: "left",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 48,
    ball: "C12",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 350,
    externalX: 380,
    externalY: 350,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 49,
    ball: "C13",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 340,
    externalX: 380,
    externalY: 340,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 50,
    ball: "C14",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 330,
    externalX: 380,
    externalY: 330,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 51,
    ball: "C15",
    signal: "VIN_18CLK",
    bodyX: 200,
    bodyY: 680,
    externalX: 180,
    externalY: 680,
    direction: "left",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 52,
    ball: "C16",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 320,
    externalX: 380,
    externalY: 320,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 53,
    ball: "C17",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 310,
    externalX: 380,
    externalY: 310,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 54,
    ball: "C18",
    signal: "VIN_18CLK",
    bodyX: 200,
    bodyY: 670,
    externalX: 180,
    externalY: 670,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 55,
    ball: "D1",
    signal: "MISO_1",
    bodyX: 910,
    bodyY: 270,
    externalX: 930,
    externalY: 270,
    direction: "right",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 56,
    ball: "D2",
    signal: "SPI_CLK_1",
    bodyX: 910,
    bodyY: 370,
    externalX: 930,
    externalY: 370,
    direction: "right",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 57,
    ball: "D3",
    signal: "SPI_CS_2",
    bodyX: 910,
    bodyY: 330,
    externalX: 930,
    externalY: 330,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 58,
    ball: "D16",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 300,
    externalX: 380,
    externalY: 300,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 59,
    ball: "D17",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 290,
    externalX: 380,
    externalY: 290,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 60,
    ball: "D18",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 280,
    externalX: 380,
    externalY: 280,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 61,
    ball: "E1",
    signal: "VDDIN",
    bodyX: 200,
    bodyY: 1010,
    externalX: 180,
    externalY: 1010,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 62,
    ball: "E2",
    signal: "SPI_CLK_2",
    bodyX: 910,
    bodyY: 340,
    externalX: 930,
    externalY: 340,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 63,
    ball: "E3",
    signal: "VSS",
    bodyX: 180,
    bodyY: 450,
    externalX: 200,
    externalY: 450,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 64,
    ball: "E16",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 270,
    externalX: 380,
    externalY: 270,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 65,
    ball: "E17",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 260,
    externalX: 380,
    externalY: 260,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 66,
    ball: "E18",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 250,
    externalX: 380,
    externalY: 250,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 67,
    ball: "F1",
    signal: "VIOIN_18_3",
    bodyX: 200,
    bodyY: 840,
    externalX: 180,
    externalY: 840,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 68,
    ball: "F2",
    signal: "MOSI_1",
    bodyX: 910,
    bodyY: 280,
    externalX: 930,
    externalY: 280,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 69,
    ball: "F3",
    signal: "VSS",
    bodyX: 180,
    bodyY: 440,
    externalX: 200,
    externalY: 440,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 70,
    ball: "F16",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 240,
    externalX: 380,
    externalY: 240,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 71,
    ball: "F17",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 230,
    externalX: 380,
    externalY: 230,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 72,
    ball: "F18",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 220,
    externalX: 380,
    externalY: 220,
    direction: "right",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 73,
    ball: "G1",
    signal: "MOSI_2",
    bodyX: 910,
    bodyY: 250,
    externalX: 930,
    externalY: 250,
    direction: "right",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 74,
    ball: "G2",
    signal: "QSPI_1",
    bodyX: 910,
    bodyY: 450,
    externalX: 930,
    externalY: 450,
    direction: "right",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 75,
    ball: "G3",
    signal: "MISO_2",
    bodyX: 910,
    bodyY: 240,
    externalX: 930,
    externalY: 240,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 76,
    ball: "G16",
    signal: "VOUT_PA",
    bodyX: 380,
    bodyY: 950,
    externalX: 400,
    externalY: 950,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 77,
    ball: "G17",
    signal: "VOUT_PA",
    bodyX: 380,
    bodyY: 940,
    externalX: 400,
    externalY: 940,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 78,
    ball: "G18",
    signal: "VOUT_PA",
    bodyX: 380,
    bodyY: 930,
    externalX: 400,
    externalY: 930,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 79,
    ball: "H1",
    signal: "VIOIN_2",
    bodyX: 200,
    bodyY: 890,
    externalX: 180,
    externalY: 890,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 80,
    ball: "H2",
    signal: "QSPI_CLK",
    bodyX: 910,
    bodyY: 400,
    externalX: 930,
    externalY: 400,
    direction: "right",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 81,
    ball: "H3",
    signal: "QSPI_0",
    bodyX: 910,
    bodyY: 460,
    externalX: 930,
    externalY: 460,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 82,
    ball: "H16",
    signal: "VIN_13RF2",
    bodyX: 200,
    bodyY: 760,
    externalX: 180,
    externalY: 760,
    direction: "left",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 83,
    ball: "H17",
    signal: "VIN_13RF2",
    bodyX: 200,
    bodyY: 750,
    externalX: 180,
    externalY: 750,
    direction: "left",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 84,
    ball: "H18",
    signal: "VIN_13RF2",
    bodyX: 200,
    bodyY: 740,
    externalX: 180,
    externalY: 740,
    direction: "left",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 85,
    ball: "J1",
    signal: "VDDIN",
    bodyX: 200,
    bodyY: 1000,
    externalX: 180,
    externalY: 1000,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 86,
    ball: "J2",
    signal: "QSPI_CS",
    bodyX: 910,
    bodyY: 410,
    externalX: 930,
    externalY: 410,
    direction: "right",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 87,
    ball: "J3",
    signal: "QSPI_2",
    bodyX: 910,
    bodyY: 440,
    externalX: 930,
    externalY: 440,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 88,
    ball: "J16",
    signal: "VIN_13RF1",
    bodyX: 200,
    bodyY: 800,
    externalX: 180,
    externalY: 800,
    direction: "left",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 89,
    ball: "J17",
    signal: "VIN_13RF1",
    bodyX: 200,
    bodyY: 790,
    externalX: 180,
    externalY: 790,
    direction: "left",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 90,
    ball: "J18",
    signal: "VIN_13RF1",
    bodyX: 200,
    bodyY: 780,
    externalX: 180,
    externalY: 780,
    direction: "left",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 91,
    ball: "K1",
    signal: "VIOIN_18_2",
    bodyX: 200,
    bodyY: 860,
    externalX: 180,
    externalY: 860,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 92,
    ball: "K2",
    signal: "QSPI_3",
    bodyX: 910,
    bodyY: 430,
    externalX: 930,
    externalY: 430,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 93,
    ball: "K3",
    signal: "GPIO_2",
    bodyX: 950,
    bodyY: 620,
    externalX: 970,
    externalY: 620,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 94,
    ball: "K16",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 210,
    externalX: 380,
    externalY: 210,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 95,
    ball: "K17",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 200,
    externalX: 380,
    externalY: 200,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 96,
    ball: "K18",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 190,
    externalX: 380,
    externalY: 190,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 97,
    ball: "L1",
    signal: "DP7",
    bodyX: 950,
    bodyY: 810,
    externalX: 970,
    externalY: 810,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 98,
    ball: "L2",
    signal: "DP6",
    bodyX: 950,
    bodyY: 820,
    externalX: 970,
    externalY: 820,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 99,
    ball: "L3",
    signal: "GPIO_1",
    bodyX: 950,
    bodyY: 630,
    externalX: 970,
    externalY: 630,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 100,
    ball: "L16",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 180,
    externalX: 380,
    externalY: 180,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 101,
    ball: "L17",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 170,
    externalX: 380,
    externalY: 170,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 102,
    ball: "L18",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 160,
    externalX: 380,
    externalY: 160,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 103,
    ball: "M1",
    signal: "DP5",
    bodyX: 950,
    bodyY: 830,
    externalX: 970,
    externalY: 830,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 104,
    ball: "M2",
    signal: "GPIO_0",
    bodyX: 950,
    bodyY: 640,
    externalX: 970,
    externalY: 640,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 105,
    ball: "M3",
    signal: "SYNC_OUT",
    bodyX: 780,
    bodyY: 790,
    externalX: 760,
    externalY: 790,
    direction: "left",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 106,
    ball: "M16",
    signal: "VIN_18BB",
    bodyX: 200,
    bodyY: 720,
    externalX: 180,
    externalY: 720,
    direction: "left",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 107,
    ball: "M17",
    signal: "VIN_18BB",
    bodyX: 200,
    bodyY: 710,
    externalX: 180,
    externalY: 710,
    direction: "left",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 108,
    ball: "M18",
    signal: "VIN_18BB",
    bodyX: 200,
    bodyY: 700,
    externalX: 180,
    externalY: 700,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 109,
    ball: "N1",
    signal: "LVDS_TXM_0",
    bodyX: 680,
    bodyY: 280,
    externalX: 660,
    externalY: 280,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 110,
    ball: "N2",
    signal: "LVDS_TXP_0",
    bodyX: 680,
    bodyY: 270,
    externalX: 660,
    externalY: 270,
    direction: "left",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 111,
    ball: "N3",
    signal: "VSS",
    bodyX: 180,
    bodyY: 430,
    externalX: 200,
    externalY: 430,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 112,
    ball: "N16",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 150,
    externalX: 380,
    externalY: 150,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 113,
    ball: "N17",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 140,
    externalX: 380,
    externalY: 140,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 114,
    ball: "N18",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 130,
    externalX: 380,
    externalY: 130,
    direction: "right",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 115,
    ball: "P1",
    signal: "LVDS_TXM_1",
    bodyX: 680,
    bodyY: 250,
    externalX: 660,
    externalY: 250,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 116,
    ball: "P2",
    signal: "LVDS_TXP_1",
    bodyX: 680,
    bodyY: 240,
    externalX: 660,
    externalY: 240,
    direction: "left",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 117,
    ball: "P3",
    signal: "VSS",
    bodyX: 180,
    bodyY: 420,
    externalX: 200,
    externalY: 420,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 118,
    ball: "P16",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 120,
    externalX: 380,
    externalY: 120,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 119,
    ball: "P17",
    signal: "GPADC_2",
    bodyX: 950,
    bodyY: 700,
    externalX: 970,
    externalY: 700,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 120,
    ball: "P18",
    signal: "GPADC_1",
    bodyX: 950,
    bodyY: 710,
    externalX: 970,
    externalY: 710,
    direction: "right",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 121,
    ball: "R1",
    signal: "LVDS_CLKP",
    bodyX: 680,
    bodyY: 340,
    externalX: 660,
    externalY: 340,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 122,
    ball: "R2",
    signal: "LVDS_CLKM",
    bodyX: 680,
    bodyY: 330,
    externalX: 660,
    externalY: 330,
    direction: "left",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 123,
    ball: "R3",
    signal: "VSS",
    bodyX: 180,
    bodyY: 410,
    externalX: 200,
    externalY: 410,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 124,
    ball: "R16",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 110,
    externalX: 380,
    externalY: 110,
    direction: "right",
  },
  {
    unit: "U2E",
    sheet: "power",
    pinNumber: 125,
    ball: "R17",
    signal: "VSSA",
    bodyX: 360,
    bodyY: 100,
    externalX: 380,
    externalY: 100,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 126,
    ball: "R18",
    signal: "GPADC_3",
    bodyX: 950,
    bodyY: 690,
    externalX: 970,
    externalY: 690,
    direction: "right",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 127,
    ball: "T1",
    signal: "LVDS_FRCLKP",
    bodyX: 680,
    bodyY: 310,
    externalX: 660,
    externalY: 310,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 128,
    ball: "T2",
    signal: "LVDS_FRCLKM",
    bodyX: 680,
    bodyY: 300,
    externalX: 660,
    externalY: 300,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 129,
    ball: "T3",
    signal: "TCK",
    bodyX: 680,
    bodyY: 390,
    externalX: 660,
    externalY: 390,
    direction: "left",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 130,
    ball: "T4",
    signal: "VSS",
    bodyX: 180,
    bodyY: 400,
    externalX: 200,
    externalY: 400,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 131,
    ball: "T5",
    signal: "VSS",
    bodyX: 180,
    bodyY: 390,
    externalX: 200,
    externalY: 390,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 132,
    ball: "T6",
    signal: "VSS",
    bodyX: 180,
    bodyY: 380,
    externalX: 200,
    externalY: 380,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 133,
    ball: "T7",
    signal: "VSS",
    bodyX: 180,
    bodyY: 370,
    externalX: 200,
    externalY: 370,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 134,
    ball: "T8",
    signal: "VSS",
    bodyX: 180,
    bodyY: 360,
    externalX: 200,
    externalY: 360,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 135,
    ball: "T9",
    signal: "VSS",
    bodyX: 180,
    bodyY: 350,
    externalX: 200,
    externalY: 350,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 136,
    ball: "T10",
    signal: "VSS",
    bodyX: 180,
    bodyY: 340,
    externalX: 200,
    externalY: 340,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 137,
    ball: "T11",
    signal: "VSS",
    bodyX: 180,
    bodyY: 330,
    externalX: 200,
    externalY: 330,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 138,
    ball: "T12",
    signal: "VSS",
    bodyX: 180,
    bodyY: 320,
    externalX: 200,
    externalY: 320,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 139,
    ball: "T13",
    signal: "VSS",
    bodyX: 180,
    bodyY: 310,
    externalX: 200,
    externalY: 310,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 140,
    ball: "T14",
    signal: "VSS",
    bodyX: 180,
    bodyY: 300,
    externalX: 200,
    externalY: 300,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 141,
    ball: "T15",
    signal: "VSS",
    bodyX: 180,
    bodyY: 290,
    externalX: 200,
    externalY: 290,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 142,
    ball: "T16",
    signal: "VSS",
    bodyX: 180,
    bodyY: 280,
    externalX: 200,
    externalY: 280,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 143,
    ball: "T17",
    signal: "VSSA",
    bodyX: 180,
    bodyY: 150,
    externalX: 200,
    externalY: 150,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 144,
    ball: "T18",
    signal: "GPADC_4",
    bodyX: 950,
    bodyY: 680,
    externalX: 970,
    externalY: 680,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 145,
    ball: "U1",
    signal: "VSS",
    bodyX: 180,
    bodyY: 270,
    externalX: 200,
    externalY: 270,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 146,
    ball: "U2",
    signal: "VIOIN_18DIFF",
    bodyX: 200,
    bodyY: 830,
    externalX: 180,
    externalY: 830,
    direction: "left",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 147,
    ball: "U3",
    signal: "DMM_CLK",
    bodyX: 780,
    bodyY: 630,
    externalX: 760,
    externalY: 630,
    direction: "left",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 148,
    ball: "U4",
    signal: "DMM_SYNC",
    bodyX: 780,
    bodyY: 620,
    externalX: 760,
    externalY: 620,
    direction: "left",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 149,
    ball: "U5",
    signal: "DP3",
    bodyX: 950,
    bodyY: 850,
    externalX: 970,
    externalY: 850,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 150,
    ball: "U6",
    signal: "DP1",
    bodyX: 950,
    bodyY: 870,
    externalX: 970,
    externalY: 870,
    direction: "right",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 151,
    ball: "U7",
    signal: "DP0",
    bodyX: 950,
    bodyY: 880,
    externalX: 970,
    externalY: 880,
    direction: "right",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 152,
    ball: "U8",
    signal: "TMS",
    bodyX: 680,
    bodyY: 380,
    externalX: 660,
    externalY: 380,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 153,
    ball: "U9",
    signal: "TDI",
    bodyX: 680,
    bodyY: 410,
    externalX: 660,
    externalY: 410,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 154,
    ball: "U10",
    signal: "TDO",
    bodyX: 680,
    bodyY: 400,
    externalX: 660,
    externalY: 400,
    direction: "left",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 155,
    ball: "U11",
    signal: "RESET",
    bodyX: 780,
    bodyY: 880,
    externalX: 760,
    externalY: 880,
    direction: "left",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 156,
    ball: "U12",
    signal: "SYNC_IN",
    bodyX: 780,
    bodyY: 800,
    externalX: 760,
    externalY: 800,
    direction: "left",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 157,
    ball: "U13",
    signal: "WARM_RESET",
    bodyX: 780,
    bodyY: 860,
    externalX: 760,
    externalY: 860,
    direction: "left",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 158,
    ball: "U14",
    signal: "ERROR_IN",
    bodyX: 780,
    bodyY: 760,
    externalX: 760,
    externalY: 760,
    direction: "left",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 159,
    ball: "U15",
    signal: "ERROR_OUT",
    bodyX: 780,
    bodyY: 750,
    externalX: 760,
    externalY: 750,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 160,
    ball: "U16",
    signal: "RS232_TX",
    bodyX: 680,
    bodyY: 460,
    externalX: 660,
    externalY: 460,
    direction: "left",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 161,
    ball: "U17",
    signal: "VSSA",
    bodyX: 180,
    bodyY: 140,
    externalX: 200,
    externalY: 140,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 162,
    ball: "U18",
    signal: "VSSA",
    bodyX: 180,
    bodyY: 130,
    externalX: 200,
    externalY: 130,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 163,
    ball: "V1",
    signal: "VSS",
    bodyX: 180,
    bodyY: 260,
    externalX: 200,
    externalY: 260,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 164,
    ball: "V2",
    signal: "VPP",
    bodyX: 200,
    bodyY: 950,
    externalX: 180,
    externalY: 950,
    direction: "left",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 165,
    ball: "V3",
    signal: "DP4",
    bodyX: 950,
    bodyY: 840,
    externalX: 970,
    externalY: 840,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 166,
    ball: "V4",
    signal: "VDDIN",
    bodyX: 200,
    bodyY: 990,
    externalX: 180,
    externalY: 990,
    direction: "left",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 167,
    ball: "V5",
    signal: "DP2",
    bodyX: 950,
    bodyY: 860,
    externalX: 970,
    externalY: 860,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 168,
    ball: "V6",
    signal: "VIN_SRAM_2",
    bodyX: 200,
    bodyY: 610,
    externalX: 180,
    externalY: 610,
    direction: "left",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 169,
    ball: "V7",
    signal: "VNWA_2",
    bodyX: 380,
    bodyY: 1000,
    externalX: 400,
    externalY: 1000,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 170,
    ball: "V8",
    signal: "VDDIN",
    bodyX: 200,
    bodyY: 980,
    externalX: 180,
    externalY: 980,
    direction: "left",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 171,
    ball: "V9",
    signal: "VIOIN_1",
    bodyX: 200,
    bodyY: 910,
    externalX: 180,
    externalY: 910,
    direction: "left",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 172,
    ball: "V10",
    signal: "PMIC_CLKOUT",
    bodyX: 780,
    bodyY: 720,
    externalX: 760,
    externalY: 720,
    direction: "left",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 173,
    ball: "V11",
    signal: "VIOIN_18_1",
    bodyX: 200,
    bodyY: 870,
    externalX: 180,
    externalY: 870,
    direction: "left",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 174,
    ball: "V12",
    signal: "VIN_SRAM_1",
    bodyX: 200,
    bodyY: 620,
    externalX: 180,
    externalY: 620,
    direction: "left",
  },
  {
    unit: "U2A",
    sheet: "io",
    pinNumber: 175,
    ball: "V13",
    signal: "MCU_CLKOUT",
    bodyX: 780,
    bodyY: 700,
    externalX: 760,
    externalY: 700,
    direction: "left",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 176,
    ball: "V14",
    signal: "VNWA_1",
    bodyX: 380,
    bodyY: 1010,
    externalX: 400,
    externalY: 1010,
    direction: "right",
  },
  {
    unit: "U2C",
    sheet: "power",
    pinNumber: 177,
    ball: "V15",
    signal: "VDDIN",
    bodyX: 200,
    bodyY: 970,
    externalX: 180,
    externalY: 970,
    direction: "left",
  },
  {
    unit: "U2B",
    sheet: "io",
    pinNumber: 178,
    ball: "V16",
    signal: "RS232_RX",
    bodyX: 680,
    bodyY: 450,
    externalX: 660,
    externalY: 450,
    direction: "left",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 179,
    ball: "V17",
    signal: "VSSA",
    bodyX: 180,
    bodyY: 120,
    externalX: 200,
    externalY: 120,
    direction: "right",
  },
  {
    unit: "U2D",
    sheet: "power",
    pinNumber: 180,
    ball: "V18",
    signal: "VSSA",
    bodyX: 180,
    bodyY: 110,
    externalX: 200,
    externalY: 110,
    direction: "right",
  },
] as const;

const AWR_NET_CONNECTIONS = [
  { net: "AR_1P0_RF1", balls: ["J16", "J17", "J18"] },
  { net: "AR_1P0_RF2", balls: ["G16", "G17", "G18", "H16", "H17", "H18"] },
  {
    net: "AR_1P2",
    balls: [
      "A5",
      "C1",
      "E1",
      "J1",
      "V4",
      "V6",
      "V7",
      "V8",
      "V12",
      "V14",
      "V15",
    ],
  },
  { net: "AR_1V4_APLL", balls: ["A10"] },
  { net: "AR_1V4_SYNTH", balls: ["A9"] },
  {
    net: "AR_1V8",
    balls: [
      "A12",
      "B1",
      "C11",
      "C15",
      "C18",
      "F1",
      "H1",
      "K1",
      "M16",
      "M17",
      "M18",
      "U2",
      "V11",
    ],
  },
  { net: "AR_BSS_LOGGER", balls: ["D3"] },
  { net: "AR_CS1", balls: ["C2"] },
  { net: "AR_DMM_CLK", balls: ["U3"] },
  { net: "AR_DMM_SYNC", balls: ["U4"] },
  { net: "AR_DP0", balls: ["U7"] },
  { net: "AR_DP1", balls: ["U6"] },
  { net: "AR_DP2", balls: ["V5"] },
  { net: "AR_DP3", balls: ["U5"] },
  { net: "AR_DP4", balls: ["V3"] },
  { net: "AR_DP5", balls: ["M1"] },
  { net: "AR_DP6", balls: ["L2"] },
  { net: "AR_DP7", balls: ["L1"] },
  { net: "AR_GPADC_1", balls: ["P18"] },
  { net: "AR_GPADC_2", balls: ["P17"] },
  { net: "AR_GPADC_3", balls: ["R18"] },
  { net: "AR_GPADC_4", balls: ["T18"] },
  { net: "AR_GPADC_5", balls: ["C9"] },
  { net: "AR_GPADC_6", balls: ["C10"] },
  { net: "AR_GPIO_0", balls: ["M2"] },
  { net: "AR_GPIO_1", balls: ["L3"] },
  { net: "AR_GPIO_2", balls: ["K3"] },
  { net: "AR_HOSTINTR1", balls: ["B2"] },
  { net: "AR_LVDS_0_N", balls: ["N1"] },
  { net: "AR_LVDS_0_P", balls: ["N2"] },
  { net: "AR_LVDS_1_N", balls: ["P1"] },
  { net: "AR_LVDS_1_P", balls: ["P2"] },
  { net: "AR_LVDS_CLK_N", balls: ["R2"] },
  { net: "AR_LVDS_CLK_P", balls: ["R1"] },
  { net: "AR_LVDS_FRCLK_N", balls: ["T2"] },
  { net: "AR_LVDS_FRCLK_P", balls: ["T1"] },
  { net: "AR_MCUCLKOUT", balls: ["V13"] },
  { net: "AR_MISO1", balls: ["D1"] },
  { net: "AR_MOSI1", balls: ["F2"] },
  { net: "AR_MSS_LOGGER", balls: ["E2"] },
  { net: "AR_NERR_OUT", balls: ["U15"] },
  { net: "AR_NERRIN", balls: ["U14"] },
  { net: "AR_NRST", balls: ["U11"] },
  { net: "AR_OSC_CLKOUT", balls: ["A14"] },
  { net: "AR_PMIC_CLKOUT_SOP2", balls: ["V10"] },
  { net: "AR_QSPI_CLK", balls: ["H2"] },
  { net: "AR_QSPI_CS", balls: ["J2"] },
  { net: "AR_QSPI_D0", balls: ["H3"] },
  { net: "AR_QSPI_D1", balls: ["G2"] },
  { net: "AR_QSPI_D2", balls: ["J3"] },
  { net: "AR_QSPI_D3", balls: ["K2"] },
  { net: "AR_RS232RX", balls: ["V16"] },
  { net: "AR_RS232TX", balls: ["U16"] },
  { net: "AR_SCL", balls: ["G3"] },
  { net: "AR_SDA", balls: ["G1"] },
  { net: "AR_SPICLK1", balls: ["D2"] },
  { net: "AR_SYNC_IN", balls: ["U12"] },
  { net: "AR_SYNC_OUT_SOP1", balls: ["M3"] },
  { net: "AR_TCK", balls: ["T3"] },
  { net: "AR_TDI", balls: ["U9"] },
  { net: "AR_TDO_SOP0", balls: ["U10"] },
  { net: "AR_TMS", balls: ["U8"] },
  { net: "AR_VBGAP", balls: ["A16"] },
  { net: "AR_VPP", balls: ["V2"] },
  { net: "AR_WARMRST", balls: ["U13"] },
  { net: "AR_XTAL_N", balls: ["B7"] },
  { net: "AR_XTAL_P", balls: ["A7"] },
  {
    net: "GND",
    balls: [
      "A1",
      "A2",
      "A6",
      "A8",
      "A11",
      "A13",
      "A15",
      "A17",
      "A18",
      "B6",
      "B8",
      "B9",
      "B10",
      "B11",
      "B12",
      "B13",
      "B14",
      "B15",
      "B16",
      "B17",
      "B18",
      "C6",
      "C7",
      "C8",
      "C12",
      "C13",
      "C14",
      "C16",
      "C17",
      "D16",
      "D17",
      "D18",
      "E3",
      "E16",
      "E17",
      "E18",
      "F3",
      "F16",
      "F17",
      "F18",
      "K16",
      "K17",
      "K18",
      "L16",
      "L17",
      "L18",
      "N3",
      "N16",
      "N17",
      "N18",
      "P3",
      "P16",
      "R3",
      "R16",
      "R17",
      "T4",
      "T5",
      "T6",
      "T7",
      "T8",
      "T9",
      "T10",
      "T11",
      "T12",
      "T13",
      "T14",
      "T15",
      "T16",
      "T17",
      "U1",
      "U17",
      "U18",
      "V1",
      "V17",
      "V18",
    ],
  },
  { net: "PMIC_3V3", balls: ["V9"] },
] as const;

export const RADAR_SOC_INTERFACE_NETS = [
  ...AWR_NET_CONNECTIONS.map(({ net }) => net),
  "PMIC_CLK",
  "SOP0",
  "SOP1",
];

const IO_PORT_LABELS = [
  { net: "PMIC_CLK", sourceX: 1200, sourceY: 830 },
  { net: "SOP1", sourceX: 1370, sourceY: 630 },
  { net: "SOP0", sourceX: 1370, sourceY: 440 },
  { net: "AR_SCL", sourceX: 1030, sourceY: 240 },
  { net: "AR_MISO1", sourceX: 1030, sourceY: 270 },
  { net: "AR_MOSI1", sourceX: 1030, sourceY: 280 },
  { net: "AR_SDA", sourceX: 1030, sourceY: 250 },
  { net: "AR_QSPI_D0", sourceX: 1030, sourceY: 460 },
  { net: "AR_QSPI_D1", sourceX: 1030, sourceY: 450 },
  { net: "AR_QSPI_D2", sourceX: 1030, sourceY: 440 },
  { net: "AR_QSPI_D3", sourceX: 1030, sourceY: 430 },
  { net: "AR_RS232TX", sourceX: 470, sourceY: 460 },
  { net: "AR_RS232RX", sourceX: 470, sourceY: 450 },
  { net: "AR_TDO_SOP0", sourceX: 460, sourceY: 400 },
  { net: "AR_TCK", sourceX: 490, sourceY: 390 },
  { net: "AR_TMS", sourceX: 490, sourceY: 380 },
  { net: "AR_TDI", sourceX: 490, sourceY: 410 },
  { net: "AR_LVDS_CLK_N", sourceX: 450, sourceY: 330 },
  { net: "AR_LVDS_CLK_P", sourceX: 450, sourceY: 340 },
  { net: "AR_LVDS_FRCLK_N", sourceX: 440, sourceY: 300 },
  { net: "AR_LVDS_FRCLK_P", sourceX: 440, sourceY: 310 },
  { net: "AR_CS1", sourceX: 1030, sourceY: 360 },
  { net: "AR_BSS_LOGGER", sourceX: 1030, sourceY: 330 },
  { net: "AR_HOSTINTR1", sourceX: 1030, sourceY: 310 },
  { net: "AR_SPICLK1", sourceX: 1030, sourceY: 370 },
  { net: "AR_MSS_LOGGER", sourceX: 1030, sourceY: 340 },
  { net: "AR_QSPI_CLK", sourceX: 1030, sourceY: 400 },
  { net: "AR_QSPI_CS", sourceX: 1030, sourceY: 410 },
  { net: "AR_DP0", sourceX: 1070, sourceY: 880 },
  { net: "AR_DP1", sourceX: 1070, sourceY: 870 },
  { net: "AR_DP2", sourceX: 1070, sourceY: 860 },
  { net: "AR_DP3", sourceX: 1070, sourceY: 850 },
  { net: "AR_DP4", sourceX: 1070, sourceY: 840 },
  { net: "AR_DP5", sourceX: 1070, sourceY: 830 },
  { net: "AR_DP6", sourceX: 1070, sourceY: 820 },
  { net: "AR_DP7", sourceX: 1070, sourceY: 810 },
  { net: "AR_GPIO_0", sourceX: 1020, sourceY: 640 },
  { net: "AR_GPIO_1", sourceX: 1020, sourceY: 630 },
  { net: "AR_GPIO_2", sourceX: 1020, sourceY: 620 },
  { net: "AR_DMM_SYNC", sourceX: 550, sourceY: 620 },
  { net: "AR_DMM_CLK", sourceX: 550, sourceY: 630 },
  { net: "AR_SYNC_IN", sourceX: 560, sourceY: 800 },
  { net: "AR_SYNC_OUT_SOP1", sourceX: 520, sourceY: 790 },
  { net: "AR_PMIC_CLKOUT_SOP2", sourceX: 510, sourceY: 720 },
  { net: "AR_MCUCLKOUT", sourceX: 550, sourceY: 700 },
  { net: "AR_NERRIN", sourceX: 570, sourceY: 760 },
  { net: "AR_NERR_OUT", sourceX: 550, sourceY: 750 },
  { net: "AR_NRST", sourceX: 570, sourceY: 880 },
  { net: "AR_WARMRST", sourceX: 550, sourceY: 860 },
  { net: "AR_OSC_CLKOUT", sourceX: 430, sourceY: 830 },
  { net: "AR_LVDS_0_N", sourceX: 460, sourceY: 280 },
  { net: "AR_LVDS_0_P", sourceX: 460, sourceY: 270 },
  { net: "AR_LVDS_1_P", sourceX: 460, sourceY: 240 },
  { net: "AR_LVDS_1_N", sourceX: 460, sourceY: 250 },
] as const;

const POWER_PORT_LABELS = [
  { net: "GND", sourceX: 630, sourceY: 690 },
  { net: "GND", sourceX: 880, sourceY: 690 },
  { net: "GND", sourceX: 1050, sourceY: 690 },
  { net: "GND", sourceX: 1250, sourceY: 690 },
  { net: "GND", sourceX: 1290, sourceY: 440 },
  { net: "GND", sourceX: 1420, sourceY: 440 },
  { net: "GND", sourceX: 540, sourceY: 440 },
  { net: "GND", sourceX: 790, sourceY: 440 },
  { net: "GND", sourceX: 1050, sourceY: 440 },
  { net: "GND", sourceX: 1330, sourceY: 210 },
  { net: "GND", sourceX: 1460, sourceY: 210 },
  { net: "GND", sourceX: 850, sourceY: 200 },
  { net: "GND", sourceX: 760, sourceY: 200 },
  { net: "GND", sourceX: 690, sourceY: 200 },
  { net: "PMIC_3V3", sourceX: 1050, sourceY: 530 },
  { net: "AR_1V8", sourceX: 630, sourceY: 770 },
  { net: "AR_1V8", sourceX: 880, sourceY: 780 },
  { net: "AR_1V8", sourceX: 1050, sourceY: 780 },
  { net: "AR_VBGAP", sourceX: 1290, sourceY: 530 },
  { net: "AR_1P0_RF2", sourceX: 1420, sourceY: 530 },
  { net: "AR_1P0_RF1", sourceX: 540, sourceY: 530 },
  { net: "AR_1P0_RF2", sourceX: 790, sourceY: 530 },
  { net: "AR_1V4_SYNTH", sourceX: 1330, sourceY: 300 },
  { net: "AR_1V4_APLL", sourceX: 1460, sourceY: 300 },
  { net: "AR_1P2", sourceX: 690, sourceY: 310 },
  { net: "GND", sourceX: 400, sourceY: 90 },
  { net: "GND", sourceX: 220, sourceY: 100 },
  { net: "AR_1V8", sourceX: 140, sourceY: 720 },
  { net: "AR_1V8", sourceX: 140, sourceY: 650 },
  { net: "AR_1V8", sourceX: 140, sourceY: 680 },
  { net: "AR_1P0_RF1", sourceX: 140, sourceY: 800 },
  { net: "AR_1P0_RF2", sourceX: 140, sourceY: 760 },
  { net: "AR_1P0_RF2", sourceX: 440, sourceY: 950 },
  { net: "AR_1V4_APLL", sourceX: 420, sourceY: 900 },
  { net: "AR_1V4_SYNTH", sourceX: 470, sourceY: 880 },
  { net: "AR_1P2", sourceX: 120, sourceY: 620 },
  { net: "AR_1V8", sourceX: 140, sourceY: 870 },
  { net: "AR_1P2", sourceX: 440, sourceY: 1010 },
  { net: "AR_1P2", sourceX: 140, sourceY: 1010 },
  { net: "PMIC_3V3", sourceX: 140, sourceY: 910 },
  { net: "AR_VBGAP", sourceX: 90, sourceY: 930 },
  { net: "AR_1V8", sourceX: 1250, sourceY: 780 },
] as const;

const IO_RESISTORS = [
  {
    name: "R85",
    resistance: "10k",
    sourceX: 1390,
    sourceY: 740,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R84",
    resistance: "10k",
    sourceX: 1390,
    sourceY: 550,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R59",
    resistance: "10k",
    sourceX: 120,
    sourceY: 480,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R23",
    resistance: "10k",
    sourceX: 120,
    sourceY: 460,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R22",
    resistance: "10k",
    sourceX: 120,
    sourceY: 440,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R3",
    resistance: "10k",
    sourceX: 120,
    sourceY: 270,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R8",
    resistance: "10k",
    sourceX: 120,
    sourceY: 380,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R7",
    resistance: "10k",
    sourceX: 120,
    sourceY: 360,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R21",
    resistance: "10k",
    sourceX: 120,
    sourceY: 420,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R4",
    resistance: "100k",
    sourceX: 120,
    sourceY: 320,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R75",
    resistance: "1k",
    sourceX: 120,
    sourceY: 300,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R103",
    resistance: "0",
    sourceX: 1340,
    sourceY: 780,
    rotation: 270,
    doNotPlace: true,
  },
  {
    name: "R9",
    resistance: "100k",
    sourceX: 120,
    sourceY: 400,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R5",
    resistance: "100k",
    sourceX: 120,
    sourceY: 340,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R83",
    resistance: "10k",
    sourceX: 1390,
    sourceY: 360,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R2",
    resistance: "0",
    sourceX: 1600,
    sourceY: 360,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R176",
    resistance: "7.87k",
    sourceX: 1530,
    sourceY: 740,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R172",
    resistance: "82.5k",
    sourceX: 1480,
    sourceY: 700,
    rotation: 270,
    doNotPlace: false,
  },
  {
    name: "R171",
    resistance: "750",
    sourceX: 1480,
    sourceY: 590,
    rotation: 270,
    doNotPlace: false,
  },
  {
    name: "R170",
    resistance: "82.5k",
    sourceX: 1480,
    sourceY: 510,
    rotation: 270,
    doNotPlace: false,
  },
  {
    name: "R174",
    resistance: "7.87k",
    sourceX: 1520,
    sourceY: 360,
    rotation: 0,
    doNotPlace: false,
  },
  {
    name: "R159",
    resistance: "750",
    sourceX: 1480,
    sourceY: 400,
    rotation: 270,
    doNotPlace: false,
  },
  {
    name: "R158",
    resistance: "82.5k",
    sourceX: 1480,
    sourceY: 320,
    rotation: 270,
    doNotPlace: false,
  },
] as const;

const IO_TESTPOINTS = [
  { name: "TP14", sourceX: 320, sourceY: 480 },
  { name: "TP8", sourceX: 1000, sourceY: 700 },
  { name: "TP7", sourceX: 1000, sourceY: 690 },
  { name: "TP6", sourceX: 1000, sourceY: 680 },
  { name: "TP3", sourceX: 1000, sourceY: 670 },
  { name: "TP2", sourceX: 1000, sourceY: 660 },
  { name: "TP9", sourceX: 1000, sourceY: 710 },
  { name: "TP17", sourceX: 530, sourceY: 810 },
] as const;

const POWER_CAPACITORS = [
  {
    name: "C68",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 1400,
    sourceY: 725,
    rotation: 270,
    supply: "AR_1V8",
  },
  {
    name: "C67",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 1350,
    sourceY: 725,
    rotation: 270,
    supply: "AR_1V8",
  },
  {
    name: "C66",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 1300,
    sourceY: 725,
    rotation: 270,
    supply: "AR_1V8",
  },
  {
    name: "C56",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 680,
    sourceY: 725,
    rotation: 270,
    supply: "AR_1V8",
  },
  {
    name: "C57",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 730,
    sourceY: 725,
    rotation: 270,
    supply: "AR_1V8",
  },
  {
    name: "C58",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 790,
    sourceY: 725,
    rotation: 270,
    supply: "AR_1V8",
  },
  {
    name: "C60",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 930,
    sourceY: 725,
    rotation: 270,
    supply: "AR_1V8",
  },
  {
    name: "C61",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 980,
    sourceY: 725,
    rotation: 270,
    supply: "AR_1V8",
  },
  {
    name: "C63",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 1100,
    sourceY: 725,
    rotation: 270,
    supply: "AR_1V8",
  },
  {
    name: "C64",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 1140,
    sourceY: 725,
    rotation: 270,
    supply: "AR_1V8",
  },
  {
    name: "C80",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 650,
    sourceY: 475,
    rotation: 270,
    supply: "AR_1P0_RF1",
  },
  {
    name: "C81",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 700,
    sourceY: 475,
    rotation: 270,
    supply: "AR_1P0_RF1",
  },
  {
    name: "C84",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 900,
    sourceY: 475,
    rotation: 270,
    supply: "AR_1P0_RF2",
  },
  {
    name: "C85",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 950,
    sourceY: 475,
    rotation: 270,
    supply: "AR_1P0_RF2",
  },
  {
    name: "C87",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 1110,
    sourceY: 475,
    rotation: 270,
    supply: "PMIC_3V3",
  },
  {
    name: "C88",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 1170,
    sourceY: 475,
    rotation: 270,
    supply: "PMIC_3V3",
  },
  {
    name: "C94",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 910,
    sourceY: 235,
    rotation: 270,
    supply: "AR_1P2",
  },
  {
    name: "C95",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 970,
    sourceY: 235,
    rotation: 270,
    supply: "AR_1P2",
  },
  {
    name: "C96",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 1020,
    sourceY: 235,
    rotation: 270,
    supply: "AR_1P2",
  },
  {
    name: "C97",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 1070,
    sourceY: 235,
    rotation: 270,
    supply: "AR_1P2",
  },
  {
    name: "C98",
    capacitance: "0.22uF",
    footprint: "0402",
    sourceX: 1120,
    sourceY: 235,
    rotation: 270,
    supply: "AR_1P2",
  },
  {
    name: "C70",
    capacitance: "10uF",
    footprint: "0805",
    sourceX: 1420,
    sourceY: 475,
    rotation: 270,
    supply: "AR_1P0_RF2",
  },
  {
    name: "C65",
    capacitance: "10uF",
    footprint: "0805",
    sourceX: 1250,
    sourceY: 725,
    rotation: 270,
    supply: "AR_1V8",
  },
  {
    name: "C62",
    capacitance: "10uF",
    footprint: "0805",
    sourceX: 1050,
    sourceY: 725,
    rotation: 270,
    supply: "AR_1V8",
  },
  {
    name: "C59",
    capacitance: "10uF",
    footprint: "0805",
    sourceX: 880,
    sourceY: 725,
    rotation: 270,
    supply: "AR_1V8",
  },
  {
    name: "C55",
    capacitance: "10uF",
    footprint: "0805",
    sourceX: 630,
    sourceY: 725,
    rotation: 270,
    supply: "AR_1V8",
  },
  {
    name: "C78",
    capacitance: "10uF",
    footprint: "0805",
    sourceX: 540,
    sourceY: 475,
    rotation: 270,
    supply: "AR_1P0_RF1",
  },
  {
    name: "C82",
    capacitance: "10uF",
    footprint: "0805",
    sourceX: 790,
    sourceY: 475,
    rotation: 270,
    supply: "AR_1P0_RF2",
  },
  {
    name: "C91",
    capacitance: "0.1uF",
    footprint: "0402",
    sourceX: 690,
    sourceY: 235,
    rotation: 270,
    supply: "AR_1P2",
  },
  {
    name: "C92",
    capacitance: "0.1uF",
    footprint: "0402",
    sourceX: 760,
    sourceY: 235,
    rotation: 270,
    supply: "AR_1P2",
  },
  {
    name: "C102",
    capacitance: "2.2uF",
    footprint: "0603",
    sourceX: 1050,
    sourceY: 475,
    rotation: 270,
    supply: "PMIC_3V3",
  },
  {
    name: "C103",
    capacitance: "2.2uF",
    footprint: "0603",
    sourceX: 850,
    sourceY: 235,
    rotation: 270,
    supply: "AR_1P2",
  },
  {
    name: "C89",
    capacitance: "1uF",
    footprint: "0603",
    sourceX: 1330,
    sourceY: 245,
    rotation: 270,
    supply: "AR_1V4_SYNTH",
  },
  {
    name: "C90",
    capacitance: "1uF",
    footprint: "0603",
    sourceX: 1460,
    sourceY: 245,
    rotation: 270,
    supply: "AR_1V4_APLL",
  },
  {
    name: "C79",
    capacitance: "2.2uF",
    footprint: "0603",
    sourceX: 600,
    sourceY: 475,
    rotation: 270,
    supply: "AR_1P0_RF1",
  },
  {
    name: "C83",
    capacitance: "2.2uF",
    footprint: "0603",
    sourceX: 850,
    sourceY: 475,
    rotation: 270,
    supply: "AR_1P0_RF2",
  },
  {
    name: "C74",
    capacitance: "2.2uF",
    footprint: "0603",
    sourceX: 1470,
    sourceY: 475,
    rotation: 270,
    supply: "AR_1P0_RF2",
  },
  {
    name: "C69",
    capacitance: "0.047uF",
    footprint: "0402",
    sourceX: 1290,
    sourceY: 475,
    rotation: 270,
    supply: "AR_VBGAP",
  },
] as const;

const renderAwrMultiUnitSymbol = () => (
  <symbol>
    {AWR_UNIT_BOUNDS.map((unit) => {
      const left = toSchX(unit.left, unit.sheet);
      const right = toSchX(unit.right, unit.sheet);
      const bottom = toSchY(unit.bottom);
      const top = toSchY(unit.top);
      return (
        <Fragment key={unit.unit}>
          <schematicrect
            schX={(left + right) / 2}
            schY={(bottom + top) / 2}
            width={right - left}
            height={top - bottom}
            strokeWidth={0}
            color="#fff8b5"
            isFilled
          />
          <schematicrect
            schX={(left + right) / 2}
            schY={(bottom + top) / 2}
            width={right - left}
            height={top - bottom}
            strokeWidth={0.03}
            color="#8b5a00"
          />
          <schematictext
            text={unit.unit}
            schX={left - 0.5}
            schY={top + 0.3}
            fontSize={0.24}
            anchor="bottom_left"
          />
        </Fragment>
      );
    })}
    {AWR_UNIT_PINS.map((pin) => {
      const externalX = toSchX(pin.externalX, pin.sheet);
      const externalY = toSchY(pin.externalY);
      const bodyX = toSchX(pin.bodyX, pin.sheet);
      const bodyY = toSchY(pin.bodyY);
      const isLeft = pin.direction === "left";
      return (
        <Fragment key={pin.ball}>
          <port
            name={`pin${pin.pinNumber}`}
            pinNumber={pin.pinNumber}
            schX={externalX}
            schY={externalY}
            direction={pin.direction}
            schStemLength={Math.hypot(externalX - bodyX, externalY - bodyY)}
          />
          <schematictext
            text={pin.signal}
            schX={bodyX + (isLeft ? 0.12 : -0.12)}
            schY={bodyY}
            fontSize={0.15}
            anchor={isLeft ? "left" : "right"}
          />
          <schematictext
            text={pin.ball}
            schX={bodyX + (isLeft ? -0.08 : 0.08)}
            schY={bodyY}
            fontSize={0.13}
            anchor={isLeft ? "right" : "left"}
          />
        </Fragment>
      );
    })}
    <schematictext
      text="AWR1843AoPBGALP"
      schX={toSchX(760, "io")}
      schY={toSchY(595)}
      fontSize={0.2}
      anchor="top_left"
    />
    <schematictext
      text="AWR1843AoPBGALP"
      schX={toSchX(660, "io")}
      schY={toSchY(215)}
      fontSize={0.2}
      anchor="top_left"
    />
    <schematictext
      text="AWR1843AoPBGALP"
      schX={toSchX(180, "power")}
      schY={toSchY(570)}
      fontSize={0.2}
      anchor="top_left"
    />
  </symbol>
);

const renderInterfaceLabels = () => (
  <>
    {IO_PORT_LABELS.map((label) => (
      <Fragment key={`io-${label.net}-${label.sourceX}-${label.sourceY}`}>
        <netlabel
          net={label.net}
          schX={toSchX(label.sourceX, "io")}
          schY={toSchY(label.sourceY)}
          anchorSide={label.sourceX < 850 ? "right" : "left"}
        />
      </Fragment>
    ))}
    {POWER_PORT_LABELS.map((label) => (
      <Fragment key={`power-${label.net}-${label.sourceX}-${label.sourceY}`}>
        <netlabel
          net={label.net}
          schX={toSchX(label.sourceX, "power")}
          schY={toSchY(label.sourceY)}
          anchorSide={label.net === "GND" ? "top" : "bottom"}
        />
      </Fragment>
    ))}
  </>
);

/**
 * TIDEP-01024 AWR1843AoP I/O and AOP power sheets.
 *
 * One U2 component renders all five Altium units so the 180-ball package is
 * electrically and physically represented only once.
 *
 * Coordinate transform:
 *   schX = (AltiumX - 850) * 0.0254 + sheetOffsetX
 *   schY = (AltiumY - 550) * 0.0254
 * AOP_IO uses sheetOffsetX=0; AOP_PWR uses sheetOffsetX=45 mm.
 */
export const RadarSoc_AWR1843ARBGALPQ1 = (props: SubcircuitProps) => (
  <subcircuit {...props}>
    <schematictext
      text="AOP IO"
      schX={0}
      schY={12.2}
      fontSize={0.6}
      anchor="center"
    />
    <schematictext
      text="AOP POWER"
      schX={45}
      schY={12.2}
      fontSize={0.6}
      anchor="center"
    />
    <schematictext
      text="DECOUPLING CAPS"
      schX={50}
      schY={9.7}
      fontSize={0.46}
      anchor="center"
    />

    <AWR1843ARBGALPQ1
      name="U2"
      symbol={renderAwrMultiUnitSymbol()}
      noConnect={["A3", "A4", "B3", "B4", "B5", "C3", "C4", "C5"]}
    />

    {AWR_NET_CONNECTIONS.map((connection) => (
      <Fragment key={connection.net}>
        <trace
          name={`U2_${connection.net}`}
          path={[
            ...connection.balls.map((ball) => `.U2 > .${ball}`),
            `net.${connection.net}`,
          ]}
        />
      </Fragment>
    ))}

    {IO_RESISTORS.map((resistor) => (
      <resistor
        key={resistor.name}
        name={resistor.name}
        resistance={resistor.resistance}
        footprint="0201"
        schX={toSchX(resistor.sourceX, "io")}
        schY={toSchY(resistor.sourceY)}
        schRotation={resistor.rotation}
        doNotPlace={resistor.doNotPlace}
      />
    ))}
    <capacitor
      name="C130"
      capacitance="0.1uF"
      footprint="0402"
      schX={toSchX(270, "io")}
      schY={toSchY(455)}
      schRotation={270}
    />
    <CHS01TA name="S3" schX={toSchX(1600, "io")} schY={toSchY(740)} />

    {IO_TESTPOINTS.map((testpoint) => (
      <testpoint
        key={testpoint.name}
        name={testpoint.name}
        footprintVariant="pad"
        padShape="circle"
        width="1mm"
        height="1mm"
        schX={toSchX(testpoint.sourceX, "io")}
        schY={toSchY(testpoint.sourceY)}
      />
    ))}

    <trace
      name="IO_PULLUP_RAIL"
      path={[
        ".R59 > .pin2",
        ".R23 > .pin2",
        ".R22 > .pin2",
        ".R21 > .pin2",
        ".R9 > .pin1",
        ".R8 > .pin2",
        ".R7 > .pin2",
        ".R5 > .pin1",
        ".R4 > .pin1",
        ".R75 > .pin1",
        "net.PMIC_3V3",
      ]}
    />
    <trace
      name="NRST_PULLUP"
      path={[".R59 > .pin1", ".C130 > .pin2", ".TP14 > .pin1", "net.AR_NRST"]}
    />
    <trace name="WARMRST_PULLUP" from=".R23 > .pin1" to="net.AR_WARMRST" />
    <trace name="NERRIN_PULLUP" from=".R22 > .pin1" to="net.AR_NERRIN" />
    <trace name="NERROUT_PULLUP" from=".R21 > .pin1" to="net.AR_NERR_OUT" />
    <trace name="CS1_PULLUP" from=".R9 > .pin2" to="net.AR_CS1" />
    <trace name="SCL_PULLUP" from=".R8 > .pin1" to="net.AR_SCL" />
    <trace name="SDA_PULLUP" from=".R7 > .pin1" to="net.AR_SDA" />
    <trace name="RS232RX_PULLUP" from=".R5 > .pin2" to="net.AR_RS232RX" />
    <trace name="RS232TX_PULLUP" from=".R4 > .pin2" to="net.AR_RS232TX" />
    <trace name="SPICLK1_PULLUP" from=".R75 > .pin2" to="net.AR_SPICLK1" />
    <trace name="HOSTINTR1_PULLDOWN" from=".R3 > .pin1" to="net.AR_HOSTINTR1" />
    <trace
      name="IO_GROUND"
      path={[
        ".R3 > .pin2",
        ".C130 > .pin1",
        ".R172 > .pin1",
        ".R170 > .pin1",
        ".R158 > .pin1",
        "net.GND",
      ]}
    />

    <trace name="GPADC1_TEST" from=".TP9 > .pin1" to="net.AR_GPADC_1" />
    <trace name="GPADC2_TEST" from=".TP8 > .pin1" to="net.AR_GPADC_2" />
    <trace name="GPADC3_TEST" from=".TP7 > .pin1" to="net.AR_GPADC_3" />
    <trace name="GPADC4_TEST" from=".TP6 > .pin1" to="net.AR_GPADC_4" />
    <trace name="GPADC5_TEST" from=".TP3 > .pin1" to="net.AR_GPADC_5" />
    <trace name="GPADC6_TEST" from=".TP2 > .pin1" to="net.AR_GPADC_6" />
    <trace name="OSC_CLKOUT_TEST" from=".TP17 > .pin1" to="net.AR_OSC_CLKOUT" />

    <trace
      name="SOP2_SOURCE"
      path={[".R103 > .pin1", ".R85 > .pin1", "net.AR_PMIC_CLKOUT_SOP2"]}
    />
    <trace name="PMIC_CLK_DNP" from=".R103 > .pin2" to="net.PMIC_CLK" />
    <trace
      name="SOP2_DIVIDER_NODE"
      path={[".R85 > .pin2", ".R176 > .pin2", ".R172 > .pin2"]}
    />
    <trace name="SOP2_SWITCH" path={[".R176 > .pin1", ".S3 > .pin1"]} />
    <trace name="SOP2_SWITCH_SUPPLY" from=".S3 > .pin2" to="net.PMIC_3V3" />

    <trace name="SOP1_SOURCE" from=".R84 > .pin1" to="net.AR_SYNC_OUT_SOP1" />
    <trace
      name="SOP1_DIVIDER_NODE"
      path={[".R84 > .pin2", ".R171 > .pin1", ".R170 > .pin2"]}
    />
    <trace name="SOP1_STRAP" from=".R171 > .pin2" to="net.SOP1" />

    <trace name="SOP0_SOURCE" from=".R83 > .pin1" to="net.AR_TDO_SOP0" />
    <trace
      name="SOP0_DIVIDER_NODE"
      path={[".R83 > .pin2", ".R174 > .pin2", ".R159 > .pin1", ".R158 > .pin2"]}
    />
    <trace name="SOP0_STRAP" from=".R159 > .pin2" to="net.SOP0" />
    <trace name="SOP0_SUPPLY" path={[".R174 > .pin1", ".R2 > .pin1"]} />
    <trace name="SOP0_SUPPLY_LINK" from=".R2 > .pin2" to="net.PMIC_3V3" />

    {POWER_CAPACITORS.map((capacitor) => (
      <Fragment key={capacitor.name}>
        <capacitor
          name={capacitor.name}
          capacitance={capacitor.capacitance}
          footprint={capacitor.footprint}
          schX={toSchX(capacitor.sourceX, "power")}
          schY={toSchY(capacitor.sourceY)}
          schRotation={capacitor.rotation}
        />
        <trace
          name={`${capacitor.name}_SUPPLY`}
          from={`.${capacitor.name} > .${
            capacitor.name === "C91" || capacitor.name === "C92"
              ? "pin2"
              : "pin1"
          }`}
          to={`net.${capacitor.supply}`}
        />
        <trace
          name={`${capacitor.name}_GND`}
          from={`.${capacitor.name} > .${
            capacitor.name === "C91" || capacitor.name === "C92"
              ? "pin1"
              : "pin2"
          }`}
          to="net.GND"
        />
      </Fragment>
    ))}

    {renderInterfaceLabels()}
    {RADAR_SOC_INTERFACE_NETS.map((net) => (
      <Fragment key={`port-${net}`}>
        <port name={`INTERFACE_${net}`} connectsTo={`net.${net}`} />
      </Fragment>
    ))}
  </subcircuit>
);

export default RadarSoc_AWR1843ARBGALPQ1;
